### ISSUE TITLE
How to delete the channel when connection is lost?

### ISSUE THREAD

**Issue by jjv360** [dudleycarr/nsqjs#108]
Hi, we have a single channel per connection for each device to a topic. After a while the channel list would get very long, since channels are only ever used once by one device... How do we automatically delete the created channel when `new Reader` connection is closed?

**Comment by joshgummersall** [comment]
That's not something the library supports natively, however you can use the [delete_channel API call](http://nsq.io/components/nsqlookupd.html#deletechannel) to do this. You will have to implement that API call yourself. Essentially in the bit of code where a reader disconnects you would need to invoke the API call to delete the channel associated with that reader.

I would warn you that this is perhaps not a good idea because you might run into issues where a particular reader disconnects for an unknown reason (i.e. an uncaught exception). Perhaps your organization of topics and channels should be tweaked in a way that this is not a requirement. Each new channel has some overhead associated with it so creating a unique channel per device is probably not the more scalable solution going forward. Just some food for thought.

**Comment by jjv360** [comment]
Hi @joshgummersall, thanks we are doing the delete_channel call to the nsqlookupd but it doesn't seem to delete from nsqd (it still appears on the admin screen)... I was just hoping there was a cleaner solution...

On that point, we need to be able to send messages to all connected devices for a specific user. Any ideas on the best way to implement that? Currently we are doing one topic per user ID and one channel per device... If we do a single channel for all the user's devices, then the messages are distributed and are not received by all devices...

**Comment by dudleycarr** [comment]
@jjv360 You don't want to call the delete on the `lookupd` -- you want to only call it on the `nsqd`.

If you want to broadcast a message to all connected clients, all those clients will need to listen on the same topic with a unique channel. This topic would be in addition to the per-client topic that you currently have.

Since since doesn't seem to be an nsqjs issue, I'm going to close this issue.

**Comment by joshgummersall** [comment]
@jjv360 that makes sense and given the constraints I'm not sure there is a better way to handle message broadcast. Depending on your deployment either deleting the topics via API calls when a client disconnects or perhaps running a cron on each machine running `nsqd` makes sense.

As @dudleycarr mentioned, deleting the channel from `nsqd` is really what you need to do. In order to do that programmatically you can use the [nsqlookupd lookup](http://nsq.io/components/nsqlookupd.html#lookup) endpoint to find all producers for a given topic and then make an [nsqd delete channel](http://nsq.io/components/nsqd.html#post-channeldelete) call to each `nsqd` returned by the lookup call.
