### ISSUE TITLE
Problem of npm module in Windows 10

### ISSUE THREAD

**Issue by ayushjain198** [dudleycarr/nsqjs#125]
Hi,
I am not able to npm install the nsqjs module in Windows 10. Is this module not have support for Win 10. I am able to install the same module in Ubuntu

**Comment by dudleycarr** [comment]
nsqjs requires snappy which is dependent on C modules. I don't have access to a Windows machine to debug. Happy to accept a pull request.

**Comment by tomc974** [comment]
I had the same issue. Installing `nsqjs` would fail because it can not compile `sse4_crc32`. I tried installing Python and Visual Studio and enabling .NET Framework 3.5 (to get MSBUILD 2.0) but `node-gyp` just kept complaining about not finding some stuff...

However, I've found this workaround:

1. Enable the **Windows Subsystem for Linux** as described on [this blog post](https://blogs.technet.microsoft.com/canitpro/2016/06/07/step-by-step-enabling-bash-on-windows-10/)
2. Using `bash`, install the following components
- `sudo apt install python`
- `sudo apt install make`
- `sudo apt install g++`
3. Install `nsqjs` and launch your app from `bash` and it should work

I know, I know, it's far from ideal but at it least it works...

**Comment by Bric3d** [comment]
Had the same issue on debian, fixed by installing the packages above.
Also, if you get a "Could not locate the bindings file" error after installing the packages, delete your node_modules folder and npm install again.

**Comment by tomc974** [comment]
Having the same kind of issues with another npm package, I tried harder to find a native Windows solution. If you want to install a module that compile some C++ code with `node-gyp` you have to do the following.

1. Install Visual Studio 2017 with the C++ related features (other VS version might work too)
2. In the start menu, launch `Visual Studio 2017\Developer Command Prompt for VS 2017`
3. `cd` to your project directory and run `npm install --msvs_version=2015`

Et voilà! Your package is installed and working :-)

**Comment by dudleycarr** [comment]
This should now be resolved by #149. Version 0.9 of nsqjs will have this fixed.
