### ISSUE TITLE
race condition waiting on nsqd_connected

### ISSUE THREAD

**Issue by bcoe** [dudleycarr/nsqjs#130]
I'm writing a test suite that attempts to wait for a reader to be ready (listening on `nsqd_connected`) and then emits a message to the channel being listened on.'

There seems to be a race condition, in which the reader does not receive the dispatched message unless I wait a few `ms`.

**test code:**

```js
  describe("on('package_privacy')", () => {
    const channel = `channel_${uuid.v4()}`
    it('emits package_privacy events', (done) => {
      const client = new Client(channel)
      client.connectReader()
        .then(() => {
          client.on('package_privacy', (event) => {
            return done()
          })
          client.sendPackagePrivacyEvent('@bcoe/foo', true)
        })
    })
  })
```

**horrible-hack.js**

```js
        readers[channel].on('nsqd_connected', () => {
          // TODO: open issue on nsqjs client, and figure out
          // why the reader claims to be ready too soon.
          setTimeout(() => {
            return resolve(readers[channel])
          }, 30)
        })
```

Perhaps there's another event I should be waiting on?

**Comment by dudleycarr** [comment]
Can you please send me a full working example? You're listening to the right event. There is definitely no need for a timeout hack.

**Comment by bcoe** [comment]
@dudleycarr here is an example of the behavior I'm seeing:

https://github.com/bcoe/nsqjs-130-race-condition

Run:

`npm run test:sleep` to see the tests run with a `30ms` delay before returning the reader.

and run

`npm run test:nosleep` to run the tests without the `30ms` delay.

**Comment by dudleycarr** [comment]
Super helpful. Will debug in the AM and let you know what I find.

**Comment by dudleycarr** [comment]
OK, I believe I see the issue. By default, nsqjs has a 30sec interval between requests to nsqlookupd to discover topics. Topics do not exist unless you explicitly create them or publish a message to that topic.

What I believe is happening in your tests is that you're hoping to connect to the nsqd via lookupd right before you publish the test message. However, the topic doesn't exist yet so the Reader now waits 30 seconds before it discovers the topic created by publish the message right after the Reader is created.

There are a couple of fixes: Invert the order and publish the message first effectively creating the topic. The other option is to reduce the lookupd poll interval. This will help but it will feel unsatisfying since your test would have to wait the duration of that poll interval before the test finishes.

Let me know if this addresses the issue. If not, I'll dig further.

**Comment by bcoe** [comment]
@dudleycarr it sounds like this is most likely only going to crop up in tests and not production?

Would the reader eventually get this event once the topic is discovered 30 seconds later? just want to make sure this isn't a foot gun in production.

**Comment by dudleycarr** [comment]
You're correct. 30 seconds later it would find it. So yes, it's normal behavior for NSQ. That said, this behavior does trip up people so I'm inclined to change the client behavior to use exponential backoff to the poll interval to avoid this situation.

**Comment by dudleycarr** [comment]
@bcoe Are you all good on your side? Please re-open if you're still having issues here.
