### ISSUE TITLE
Reader subscribed to specific topic and channel,need to get only for specified channel.

### ISSUE THREAD

**Issue by newasmod** [dudleycarr/nsqjs#138]
`nsq.Reader('sample_topic1', 'channel1'`

but when request:
`http://localhost:4151/pub?channel=sample_topic1&topic=channel4` ,
 i expect to receive in reader messages for channel1, but i also got this one for channel4.
Is there ability to tell the reader to accept messages only for subscribed channel? 
How this feature should be implemented?
Also i think that i dont understand the purpose of channels, i also created so question here ` http://stackoverflow.com/questions/43836244/what-is-nsq-channels-stands-for`

**Comment by dudleycarr** [comment]
A Re easier takes a topic and then a channel. In your example, you have it reversed. That could be causing your problem.

**Comment by newasmod** [comment]
@dudleycarr i have changed the url to right :

**Comment by dudleycarr** [comment]
@newasmod Just so there's no confusion: All channels for a given topic will receive all messages sent to that topic. To put it another way, each channel gets its own copy of messages sent to the topic. 

The URL you are using above isn't doing what you're hoping it does. You cannot publish to a specific channel, only to a topic. I haven't tried, but I'm sure at best it's just ignoring the channel query parameter.

All of that said, a Reader will only process messages for its channel, not others for a given topic, channel pair.

**Comment by newasmod** [comment]
@dudleycarr excuse me, i still don't understand .  How can i make a Reader process messages only for subscribed topic+channel ?

**Comment by dudleycarr** [comment]
When you create a Reader, you have to specify both a topic and a channel, and so that Reader is specific to that topic, channel pair.

One helpful way of thinking of topic and channels is to thinking of topics as a collection of things and channels as the action you want to take on the things. For a given thing (topic message), you might want to do more than one action. Let's say you received a message with a URL in it. You want to store that URL in a database and independently you want to download that URL and save it to disk. You *should* have two different Readers on different channels for each of those actions, one for saving to the DB and the other for fetching/saving to the file system. The benefit is that if your database is slow, those messages will be processed at a different rate than the other Reader that's fetching and storing to disk. A contrived example, but hopefully makes the point.

**Comment by newasmod** [comment]
@dudleycarr Can we tell that the `channels` are something like mark for the `topic` workers -  to determine which `group`  of Readers(workers) processes the message?

**Comment by dudleycarr** [comment]
I don't follow the first part of the question regarding a mark. Also, there's no use of "group" in NSQ terminology -- I presume you're talking about a set of workers all subscribed to the same topic/channel pair?

**Comment by newasmod** [comment]
@dudleycarr Yes ! I mean some abstraction. Workers( The Readers) , that are subscribed to the same topic/channel pair. And other workers, that are subscribed to the same topic but other channel. 
But i still can understand: assume one worker(Reader) receive message- that worker becomes busy( assume that worker is writing to db), and another worker  receive same message ( assuming worker that writes to disk). Both that workers will do their work: first store to db and other to disk. But if we have two workers that writes to db and two that writes to disk, the order in which workers will process messages is random! If first message coming- it can be or by `disk worker` or by `db worker` randomly! We cant guarantee that message will processed by worker that writes to disk, if we need that message to be written to disk. And in other side if the message is already processed by first `db worker` the next message can be processed with another `db worker`-> we cant guarantee that the next message will be taken by remaining free neither `disk worker` nor `db worker` ! 
I am completely lost =( Sorry, i dont understand how to use nsq channels at all

**Comment by dudleycarr** [comment]
@newasmod Hope you managed to get sorted with nsqd terminology. Closing since I don't think there's an issue here with nsqjs.
