### ISSUE TITLE
Update/ add detail to published message

### ISSUE THREAD

**Issue by apmcodes** [dudleycarr/nsqjs#271]
Is it possible to add any custom data to the message/ message body once its published. This is to add processing data/ state on to the message itself. So in case of re-queue we know the last state. 

Tried setting msg.body - getting no setter error
Tries setting msq.rawMessage - but encoding not working (tried readUInt16BE), not sure what encoding to try in nodejs

Can you please suggest hows this is possible ...

**Comment by dudleycarr** [comment]
That's not possible. NSQ doesn't provide you with a way to modify a message that you re-queue. 

You've got a couple of options:
* Re-publish the message to the same topic but with the added metadata. You'll have to then track the number of attempts yourself. Obviously, you'll always have to mark it as finished otherwise you'll be duplicating messages.
* Use something like Redis keyed on the message ID to track the metadata about the message processing.

Hope that helps.

**Comment by apmcodes** [comment]
First of all, thank you for the very quick reply. 

Options 1 seems to fit out case. We can republish the message with new metadata and finish the message. 

Thanks once again.
