### ISSUE TITLE
Is there any limit on writer bulk publish message counts?

### ISSUE THREAD

**Issue by apmcodes** [dudleycarr/nsqjs#282]
While using the bulk/ multiple messages publish, is there any limit on messages count or byte size of the messages array?

**Comment by gbhrdt** [comment]
I just ran into this, seems to be 5242880 bytes per publish:

```
E_BAD_BODY MPUB body too big 5629025 > 5242880
```

**Comment by dudleycarr** [comment]
There is both a limit on the number of messages and the message size. Here is the protocol definition: https://nsq.io/clients/tcp_protocol_spec.html#mpub

It looks like realistically, there isn't a limit on the number of message since it's `2^32 - 1`. However, the error that @gbhrdt has run into is the maximum message size which is set as a configurable option for nsqd. See `max-body-size` in: https://nsq.io/components/nsqd.html
